name: Build NetInfo EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer ps2exe
        shell: powershell
        run: |
          Install-Module -Name ps2exe -Scope CurrentUser -Force -ErrorAction Stop

      - name: Compiler netinfo_cpam.exe
        shell: powershell
        run: |
          ps2exe .\netinfo_cpam.ps1 .\netinfo_cpam.exe -noConsole -iconFile ".\ico_wifi.ico"

      - name: Compiler netinfo_cpam_antiV.exe
        shell: powershell
        run: |
          ps2exe .\netinfo_cpam_antiV.ps1 .\netinfo_cpam_antiV.exe -noConsole -iconFile ".\ico_wifi.ico"

      - name: Compiler NetInfo_Light.exe
        shell: powershell
        run: |
          ps2exe .\NetInfo_Light.ps1 .\NetInfo_Light.exe -noConsole -iconFile ".\ico_network.ico"

      - name: Uploader les exe comme artefacts
        uses: actions/upload-artifact@v4
        with:
          name: NetInfo-EXE
          path: |
            netinfo_cpam.exe
            netinfo_cpam_antiV.exe
            NetInfo_Light.exe
          retention-days: 7
